--I got my dear chinese friend Mr. DeepSeek to generate this

-- Color constants
local stone = {160, 155, 150}
local dark_stone = {120, 115, 110}
local light_stone = {190, 185, 180}
local wood = {182, 142, 101}
local dark_wood = {130, 90, 60}
local light_wood = {200, 170, 140}
local snow = {235, 240, 250}
local ice = {210, 225, 240}
local snow_wood = {200, 195, 185}
local sand = {210, 195, 170}
local desert_stone = {195, 175, 150}
local terracotta = {185, 140, 110}
local dungeon = {80, 75, 70}
local dark_dungeon = {50, 45, 40}
local metal = {170, 170, 175}
local dark_metal = {130, 130, 135}
local water = {100, 160, 200}
local grass = {130, 160, 100}
local banner_red = {200, 50, 50}
local banner_blue = {50, 100, 200}
local banner_green = {50, 180, 80}
local banner_yellow = {220, 200, 50}
local banner_purple = {160, 80, 200}
local banner_orange = {220, 140, 40}
local banner_cyan = {50, 200, 210}
local banner_pink = {220, 100, 150}
local flesh = {210, 170, 140}
local food = {200, 160, 100}
local cloth_red = {180, 60, 60}
local cloth_blue = {60, 100, 180}
local cloth_green = {60, 160, 80}
local fire = {220, 150, 50}
local dark_fire = {180, 100, 30}
local glow = {255, 220, 150}
local leaf = {100, 180, 80}
local autumn = {200, 150, 60}
local cave = {90, 85, 80}

-- Main prop color table
local prop_colors = {
    {"inventory", {200, 200, 200}},
    {"empty", {100, 100, 100}},
    {"chest_a", wood},
    {"container_small_chest", wood},
    {"container_chest_b", wood},
    {"container_chest_c", wood},
    {"player_chest", {220, 180, 50}},
    {"locked_player_chest", {180, 150, 40}},
    {"light_sun", {255, 250, 200}},
    {"light", {255, 240, 180}},
    {"light_red", {255, 150, 150}},
    {"light_night", {100, 100, 150}},
    {"torch", fire},
    {"torch_night", dark_fire},
    {"barrier_20m", {200, 50, 50}},
    {"barrier_16m", {200, 50, 50}},
    {"barrier_8m", {200, 50, 50}},
    {"barrier_4m", {200, 50, 50}},
    {"barrier_2m", {200, 50, 50}},
    {"exit_4m", {50, 200, 50}},
    {"exit_8m", {50, 200, 50}},
    {"exit_16m", {50, 200, 50}},
    {"ai_limiter_2m", {255, 100, 255}},
    {"ai_limiter_4m", {255, 100, 255}},
    {"ai_limiter_8m", {255, 100, 255}},
    {"ai_limiter_16m", {255, 100, 255}},
    {"Shield", metal},
    {"shelves", wood},
    {"table_tavern", dark_wood},
    {"table_castle_a", dark_wood},
    {"chair_castle_a", dark_wood},
    {"pillow_a", {200, 180, 200}},
    {"pillow_b", {210, 190, 210}},
    {"pillow_c", {190, 170, 190}},
    {"interior_castle_g_square_keep_b", stone},
    {"carpet_with_pillows_a", {180, 50, 50}},
    {"carpet_with_pillows_b", {50, 50, 180}},
    {"table_round_a", wood},
    {"table_round_b", wood},
    {"fireplace_b", stone},
    {"fireplace_c", stone},
    {"sofa_a", {150, 100, 80}},
    {"sofa_b", {140, 90, 70}},
    {"ewer_a", {180, 160, 140}},
    {"end_table_a", dark_wood},
    {"fake_houses_steppe_a", sand},
    {"fake_houses_steppe_b", sand},
    {"fake_houses_steppe_c", sand},
    {"boat_destroy", dark_wood},
    {"destroy_house_a", dark_wood},
    {"destroy_house_b", dark_wood},
    {"destroy_house_c", dark_wood},
    {"destroy_heap", dark_wood},
    {"destroy_castle_a", dark_stone},
    {"destroy_castle_b", dark_stone},
    {"destroy_castle_c", dark_stone},
    {"destroy_castle_d", dark_stone},
    {"destroy_windmill", dark_wood},
    {"destroy_tree_a", dark_wood},
    {"destroy_tree_b", dark_wood},
    {"destroy_bridge_a", dark_wood},
    {"destroy_bridge_b", dark_wood},
    {"catapult", dark_wood},
    {"catapult_destructible", dark_wood},
    {"broom", wood},
    {"garlic", {230, 220, 200}},
    {"garlic_b", {230, 220, 200}},
    {"destroy_a", dark_wood},
    {"destroy_b", dark_wood},
    {"bridge_wooden", wood},
    {"bridge_wooden_snowy", snow_wood},
    {"grave_a", stone},
    {"village_house_e", wood},
    {"village_house_f", wood},
    {"village_house_g", wood},
    {"village_house_h", wood},
    {"village_house_i", wood},
    {"village_house_j", wood},
    {"village_wall_a", wood},
    {"village_wall_b", wood},
    {"village_snowy_house_a", snow_wood},
    {"village_snowy_house_b", snow_wood},
    {"village_snowy_house_c", snow_wood},
    {"village_snowy_house_d", snow_wood},
    {"village_snowy_house_e", snow_wood},
    {"village_snowy_house_f", snow_wood},
    {"town_house_steppe_a", sand},
    {"town_house_steppe_b", sand},
    {"town_house_steppe_c", sand},
    {"town_house_steppe_d", sand},
    {"town_house_steppe_e", sand},
    {"town_house_steppe_f", sand},
    {"town_house_steppe_g", sand},
    {"town_house_steppe_h", sand},
    {"town_house_steppe_i", sand},
    {"carpet_a", {180, 50, 50}},
    {"carpet_b", {50, 50, 180}},
    {"carpet_c", {180, 180, 50}},
    {"carpet_d", {50, 180, 50}},
    {"carpet_e", {180, 50, 180}},
    {"carpet_f", {50, 180, 180}},
    {"awning_a", cloth_red},
    {"awning_b", cloth_blue},
    {"awning_c", cloth_green},
    {"awning_long", cloth_red},
    {"awning_long_b", cloth_blue},
    {"awning_d", cloth_green},
    {"ship", dark_wood},
    {"ship_b", dark_wood},
    {"ship_c", dark_wood},
    {"ship_d", dark_wood},
    {"snowy_barrel_a", snow_wood},
    {"snowy_fence", snow_wood},
    {"snowy_wood_heap", snow_wood},
    {"village_snowy_stable_a", snow_wood},
    {"village_straw_house_a", {200, 190, 160}},
    {"village_stable_a", wood},
    {"village_shed_a", wood},
    {"village_shed_b", wood},
    {"dungeon_door_cell_a", dark_dungeon},
    {"dungeon_door_cell_b", dark_dungeon},
    {"dungeon_door_entry_a", dark_dungeon},
    {"dungeon_door_entry_b", dark_dungeon},
    {"dungeon_door_entry_c", dark_dungeon},
    {"dungeon_door_direction_a", dark_dungeon},
    {"dungeon_door_direction_b", dark_dungeon},
    {"dungeon_door_stairs_a", dark_dungeon},
    {"dungeon_door_stairs_b", dark_dungeon},
    {"dungeon_bed_a", dungeon},
    {"dungeon_bed_b", dungeon},
    {"torture_tool_a", dark_metal},
    {"torture_tool_b", dark_metal},
    {"torture_tool_c", dark_metal},
    {"skeleton_head", {200, 190, 180}},
    {"skeleton_bone", {200, 190, 180}},
    {"skeleton_a", {200, 190, 180}},
    {"dungeon_stairs_a", dungeon},
    {"dungeon_stairs_b", dungeon},
    {"dungeon_torture_room_a", dungeon},
    {"dungeon_entry_a", dungeon},
    {"dungeon_entry_b", dungeon},
    {"dungeon_entry_c", dungeon},
    {"dungeon_cell_a", dungeon},
    {"dungeon_cell_b", dungeon},
    {"dungeon_cell_c", dungeon},
    {"dungeon_corridor_a", dungeon},
    {"dungeon_corridor_b", dungeon},
    {"dungeon_corridor_c", dungeon},
    {"dungeon_corridor_d", dungeon},
    {"dungeon_direction_a", dungeon},
    {"dungeon_direction_b", dungeon},
    {"dungeon_room_a", dungeon},
    {"dungeon_tower_stairs_a", dungeon},
    {"dungeon_tower_cell_a", dungeon},
    {"tunnel_a", cave},
    {"tunnel_salt", {200, 195, 190}},
    {"salt_a", {200, 195, 190}},
    {"door_destructible", wood},
    {"tutorial_door_a", wood},
    {"tutorial_door_b", wood},
    {"tutorial_flag_yellow", banner_yellow},
    {"tutorial_flag_red", banner_red},
    {"tutorial_flag_blue", banner_blue},
    {"interior_prison_a", dungeon},
    {"interior_prison_b", dungeon},
    {"interior_prison_cell_a", dungeon},
    {"interior_prison_d", dungeon},
    {"arena_archery_target_a", {200, 180, 150}},
    {"archery_butt_a", {200, 180, 150}},
    {"archery_target_with_hit_a", {200, 180, 150}},
    {"dummy_a", flesh},
    {"band_a", {200, 180, 150}},
    {"arena_sign", {200, 180, 150}},
    {"castle_h_battlement_a", stone},
    {"castle_h_battlement_b", stone},
    {"castle_h_battlement_c", stone},
    {"castle_h_battlement_a2", stone},
    {"castle_h_battlement_b2", stone},
    {"castle_h_corner_a", stone},
    {"castle_h_corner_c", stone},
    {"castle_h_stairs_a", stone},
    {"castle_h_stairs_b", stone},
    {"castle_h_gatehouse_a", stone},
    {"castle_h_keep_a", stone},
    {"castle_h_keep_b", stone},
    {"castle_h_house_a", stone},
    {"castle_h_house_b", stone},
    {"castle_h_house_c", stone},
    {"castle_h_battlement_barrier", stone},
    {"full_keep_b", stone},
    {"castle_f_keep_a", stone},
    {"castle_f_battlement_a", stone},
    {"castle_f_battlement_a_destroyed", dark_stone},
    {"castle_f_battlement_b", stone},
    {"castle_f_battlement_c", stone},
    {"castle_f_battlement_d", stone},
    {"castle_f_battlement_e", stone},
    {"castle_f_sally_port_elevation", stone},
    {"castle_f_battlement_corner_a", stone},
    {"castle_f_battlement_corner_b", stone},
    {"castle_f_battlement_corner_c", stone},
    {"castle_f_door_a", dark_wood},
    {"castle_f_doors_top_a", dark_wood},
    {"castle_f_sally_door_a", dark_wood},
    {"castle_f_stairs_a", stone},
    {"castle_f_tower_a", stone},
    {"castle_f_wall_stairs_a", stone},
    {"castle_f_wall_stairs_b", stone},
    {"castle_f_wall_way_a", stone},
    {"castle_f_wall_way_b", stone},
    {"castle_f_gatehouse_a", stone},
    {"castle_g_battlement_a", stone},
    {"castle_g_battlement_a1", stone},
    {"castle_g_battlement_c", stone},
    {"castle_g_corner_a", stone},
    {"castle_g_corner_c", stone},
    {"castle_g_tower_a", stone},
    {"castle_g_gate_house", stone},
    {"castle_g_gate_house_door_a", dark_wood},
    {"castle_g_gate_house_door_b", dark_wood},
    {"castle_g_square_keep_a", stone},
    {"castle_i_battlement_a", stone},
    {"castle_i_battlement_a1", stone},
    {"castle_i_battlement_c", stone},
    {"castle_i_corner_a", stone},
    {"castle_i_corner_c", stone},
    {"castle_i_tower_a", stone},
    {"castle_i_gate_house", stone},
    {"castle_i_gate_house_door_a", dark_wood},
    {"castle_i_gate_house_door_b", dark_wood},
    {"castle_i_square_keep_a", stone},
    {"mosque_a", desert_stone},
    {"stone_minaret_a", desert_stone},
    {"stone_house_a", stone},
    {"stone_house_b", stone},
    {"stone_house_c", stone},
    {"stone_house_d", stone},
    {"stone_house_e", stone},
    {"stone_house_f", stone},
    {"banner_pole", wood},
    {"custom_banner_01", banner_red},
    {"custom_banner_02", banner_blue},
    {"banner_a", banner_red},
    {"banner_b", banner_blue},
    {"banner_c", banner_green},
    {"banner_d", banner_yellow},
    {"banner_e", banner_purple},
    {"banner_f", banner_orange},
    {"banner_g", banner_cyan},
    {"banner_h", banner_pink},
    {"banner_i", banner_red},
    {"banner_j", banner_blue},
    {"banner_k", banner_green},
    {"banner_l", banner_yellow},
    {"banner_m", banner_purple},
    {"banner_n", banner_orange},
    {"banner_o", banner_cyan},
    {"banner_p", banner_pink},
    {"banner_q", banner_red},
    {"banner_r", banner_blue},
    {"banner_s", banner_green},
    {"banner_t", banner_yellow},
    {"banner_u", banner_purple},
    {"banner_ba", banner_orange},
    {"banner_bb", banner_cyan},
    {"banner_bc", banner_pink},
    {"banner_bd", banner_red},
    {"banner_be", banner_blue},
    {"banner_bf", banner_green},
    {"banner_bg", banner_yellow},
    {"banner_bh", banner_purple},
    {"banner_bi", banner_orange},
    {"banner_bj", banner_cyan},
    {"banner_bk", banner_pink},
    {"banner_bl", banner_red},
    {"banner_bm", banner_blue},
    {"banner_bn", banner_green},
    {"banner_bo", banner_yellow},
    {"banner_bp", banner_purple},
    {"banner_bq", banner_orange},
    {"banner_br", banner_cyan},
    {"banner_bs", banner_pink},
    {"banner_bt", banner_red},
    {"banner_bu", banner_blue},
    {"banner_ca", banner_green},
    {"banner_cb", banner_yellow},
    {"banner_cc", banner_purple},
    {"banner_cd", banner_orange},
    {"banner_ce", banner_cyan},
    {"banner_cf", banner_pink},
    {"banner_cg", banner_red},
    {"banner_ch", banner_blue},
    {"banner_ci", banner_green},
    {"banner_cj", banner_yellow},
    {"banner_ck", banner_purple},
    {"banner_cl", banner_orange},
    {"banner_cm", banner_cyan},
    {"banner_cn", banner_pink},
    {"banner_co", banner_red},
    {"banner_cp", banner_blue},
    {"banner_cq", banner_green},
    {"banner_cr", banner_yellow},
    {"banner_cs", banner_purple},
    {"banner_ct", banner_orange},
    {"banner_cu", banner_cyan},
    {"banner_da", banner_pink},
    {"banner_db", banner_red},
    {"banner_dc", banner_blue},
    {"banner_dd", banner_green},
    {"banner_de", banner_yellow},
    {"banner_df", banner_purple},
    {"banner_dg", banner_orange},
    {"banner_dh", banner_cyan},
    {"banner_di", banner_pink},
    {"banner_dj", banner_red},
    {"banner_dk", banner_blue},
    {"banner_dl", banner_green},
    {"banner_dm", banner_yellow},
    {"banner_dn", banner_purple},
    {"banner_do", banner_orange},
    {"banner_dp", banner_cyan},
    {"banner_dq", banner_pink},
    {"banner_dr", banner_red},
    {"banner_ds", banner_blue},
    {"banner_dt", banner_green},
    {"banner_du", banner_yellow},
    {"banner_ea", banner_purple},
    {"banner_eb", banner_orange},
    {"banner_ec", banner_cyan},
    {"banner_ed", banner_pink},
    {"banner_ee", banner_red},
    {"banner_ef", banner_blue},
    {"banner_eg", banner_green},
    {"banner_eh", banner_yellow},
    {"banner_ei", banner_purple},
    {"banner_ej", banner_orange},
    {"banner_ek", banner_cyan},
    {"banner_el", banner_pink},
    {"banner_em", banner_red},
    {"banner_en", banner_blue},
    {"banner_eo", banner_green},
    {"banner_ep", banner_yellow},
    {"banner_eq", banner_purple},
    {"banner_er", banner_orange},
    {"banner_es", banner_cyan},
    {"banner_et", banner_pink},
    {"banner_eu", banner_red},
    {"banner_f01", banner_blue},
    {"banner_f02", banner_green},
    {"banner_f03", banner_yellow},
    {"banner_f04", banner_purple},
    {"banner_f05", banner_orange},
    {"banner_f06", banner_cyan},
    {"banner_f07", banner_pink},
    {"banner_f08", banner_red},
    {"banner_f09", banner_blue},
    {"banner_f10", banner_green},
    {"banner_f11", banner_yellow},
    {"banner_f12", banner_purple},
    {"banner_f13", banner_orange},
    {"banner_f14", banner_cyan},
    {"banner_f15", banner_pink},
    {"banner_f16", banner_red},
    {"banner_f17", banner_blue},
    {"banner_f18", banner_green},
    {"banner_f19", banner_yellow},
    {"banner_f20", banner_purple},
    {"banner_g01", banner_orange},
    {"banner_g02", banner_cyan},
    {"banner_g03", banner_pink},
    {"banner_g04", banner_red},
    {"banner_g05", banner_blue},
    {"banner_g06", banner_green},
    {"banner_g07", banner_yellow},
    {"banner_g08", banner_purple},
    {"banner_g09", banner_orange},
    {"banner_g10", banner_cyan},
    {"banner_kingdom_a", banner_red},
    {"banner_kingdom_b", banner_blue},
    {"banner_kingdom_c", banner_green},
    {"banner_kingdom_d", banner_yellow},
    {"banner_kingdom_e", banner_purple},
    {"banner_kingdom_f", banner_orange},
    {"banner_f21", banner_cyan},
    {"tavern_chair_a", dark_wood},
    {"tavern_chair_b", dark_wood},
    {"tavern_table_a", dark_wood},
    {"tavern_table_b", dark_wood},
    {"fireplace_a", stone},
    {"barrel", wood},
    {"bench_tavern", dark_wood},
    {"bench_tavern_b", dark_wood},
    {"bowl_wood", wood},
    {"chandelier_table", metal},
    {"chandelier_tavern", metal},
    {"chest_gothic", dark_wood},
    {"chest_b", wood},
    {"chest_c", wood},
    {"counter_tavern", dark_wood},
    {"cup", {200, 180, 150}},
    {"dish_metal", metal},
    {"gothic_chair", dark_wood},
    {"gothic_stool", dark_wood},
    {"grate", dark_metal},
    {"jug", {200, 180, 150}},
    {"potlamp", metal},
    {"weapon_rack", wood},
    {"weapon_rack_big", wood},
    {"tavern_barrel", wood},
    {"tavern_barrel_b", wood},
    {"merchant_sign", wood},
    {"tavern_sign", wood},
    {"sack", {200, 180, 160}},
    {"skull_a", {200, 190, 180}},
    {"skull_b", {200, 190, 180}},
    {"skull_c", {200, 190, 180}},
    {"skull_d", {200, 190, 180}},
    {"skeleton_cow", {200, 190, 180}},
    {"cupboard_a", dark_wood},
    {"box_a", wood},
    {"bucket_a", wood},
    {"straw_a", {220, 210, 170}},
    {"straw_b", {220, 210, 170}},
    {"straw_c", {220, 210, 170}},
    {"cloth_a", cloth_red},
    {"cloth_b", cloth_blue},
    {"mat_a", {200, 180, 150}},
    {"mat_b", {200, 180, 150}},
    {"mat_c", {200, 180, 150}},
    {"mat_d", {200, 180, 150}},
    {"wood_a", wood},
    {"wood_b", wood},
    {"wood_heap", wood},
    {"wood_heap_b", wood},
    {"water_well_a", wood},
    {"net_a", {200, 180, 150}},
    {"net_b", {200, 180, 150}},
    {"meat_hook", metal},
    {"cooking_pole", wood},
    {"bowl_a", {200, 180, 150}},
    {"bucket_b", wood},
    {"washtub_a", wood},
    {"washtub_b", wood},
    {"table_trunk_a", wood},
    {"chair_trunk_a", wood},
    {"chair_trunk_b", wood},
    {"chair_trunk_c", wood},
    {"table_trestle_long", wood},
    {"table_trestle_small", wood},
    {"chair_trestle", wood},
    {"wheel", wood},
    {"ladder", wood},
    {"cart", wood},
    {"village_stand", wood},
    {"wooden_stand", wood},
    {"table_small", wood},
    {"table_small_b", wood},
    {"small_timber_frame_house_a", wood},
    {"timber_frame_house_b", wood},
    {"timber_frame_house_c", wood},
    {"timber_frame_extension_a", wood},
    {"timber_frame_extension_b", wood},
    {"stone_stairs_a", stone},
    {"stone_stairs_b", stone},
    {"railing_a", stone},
    {"side_building_a", stone},
    {"battlement_a", stone},
    {"battlement_a_destroyed", dark_stone},
    {"round_tower_a", stone},
    {"small_round_tower_a", stone},
    {"small_round_tower_roof_a", stone},
    {"square_keep_a", stone},
    {"square_tower_roof_a", stone},
    {"gate_house_a", stone},
    {"gate_house_b", stone},
    {"small_wall_a", stone},
    {"small_wall_b", stone},
    {"small_wall_c", stone},
    {"small_wall_c_destroy", dark_stone},
    {"small_wall_d", stone},
    {"small_wall_e", stone},
    {"small_wall_f", stone},
    {"small_wall_f2", stone},
    {"town_house_a", stone},
    {"town_house_b", stone},
    {"town_house_c", stone},
    {"town_house_d", stone},
    {"town_house_e", stone},
    {"town_house_f", stone},
    {"town_house_g", stone},
    {"town_house_h", stone},
    {"town_house_i", stone},
    {"town_house_j", stone},
    {"town_house_l", stone},
    {"town_house_m", stone},
    {"town_house_n", stone},
    {"town_house_o", stone},
    {"town_house_p", stone},
    {"town_house_q", stone},
    {"passage_house_a", stone},
    {"passage_house_b", stone},
    {"passage_house_c", stone},
    {"passage_house_d", stone},
    {"passage_house_c_door", wood},
    {"house_extension_a", stone},
    {"house_extension_b", stone},
    {"house_extension_c", stone},
    {"house_extension_d", stone},
    {"house_extension_e", stone},
    {"house_extension_f", stone},
    {"house_extension_f2", stone},
    {"house_extension_g", stone},
    {"house_extension_g2", stone},
    {"house_extension_h", stone},
    {"house_extension_i", stone},
    {"house_roof_door", wood},
    {"door_extension_a", wood},
    {"stairs_arch_a", stone},
    {"town_house_r", stone},
    {"town_house_s", stone},
    {"town_house_t", stone},
    {"town_house_u", stone},
    {"town_house_v", stone},
    {"town_house_w", stone},
    {"town_house_y", stone},
    {"town_house_z", stone},
    {"town_house_za", stone},
    {"windmill", wood},
    {"windmill_fan_turning", wood},
    {"windmill_fan", wood},
    {"fake_house_a", stone},
    {"fake_house_b", stone},
    {"fake_house_c", stone},
    {"fake_house_d", stone},
    {"fake_house_e", stone},
    {"fake_house_f", stone},
    {"fake_house_snowy_a", snow_wood},
    {"fake_house_snowy_b", snow_wood},
    {"fake_house_snowy_c", snow_wood},
    {"fake_house_snowy_d", snow_wood},
    {"fake_house_far_a", {180, 175, 170}},
    {"fake_house_far_b", {180, 175, 170}},
    {"fake_house_far_c", {180, 175, 170}},
    {"fake_house_far_d", {180, 175, 170}},
    {"fake_house_far_e", {180, 175, 170}},
    {"fake_house_far_f", {180, 175, 170}},
    {"fake_house_far_snowycrude_a", snow},
    {"fake_house_far_snowy_b", snow},
    {"fake_house_far_snowy_c", snow},
    {"fake_house_far_snowy_d", snow},
    {"earth_wall_a", {180, 160, 130}},
    {"earth_wall_a2", {180, 160, 130}},
    {"earth_wall_b", {180, 160, 130}},
    {"earth_wall_b2", {180, 160, 130}},
    {"earth_stairs_a", {180, 160, 130}},
    {"earth_stairs_b", {180, 160, 130}},
    {"earth_tower_small_a", {180, 160, 130}},
    {"earth_gate_house_a", {180, 160, 130}},
    {"earth_gate_a", {180, 160, 130}},
    {"earth_square_keep_a", {180, 160, 130}},
    {"earth_house_a", {180, 160, 130}},
    {"earth_house_b", {180, 160, 130}},
    {"earth_house_c", {180, 160, 130}},
    {"earth_house_d", {180, 160, 130}},
    {"village_steppe_a", sand},
    {"village_steppe_b", sand},
    {"village_steppe_c", sand},
    {"village_steppe_d", sand},
    {"village_steppe_e", sand},
    {"village_steppe_f", sand},
    {"town_house_aa", stone},
    {"snowy_house_a", snow_wood},
    {"snowy_house_b", snow_wood},
    {"snowy_house_c", snow_wood},
    {"snowy_house_d", snow_wood},
    {"snowy_house_e", snow_wood},
    {"snowy_house_f", snow_wood},
    {"snowy_house_g", snow_wood},
    {"snowy_house_h", snow_wood},
    {"snowy_house_i", snow_wood},
    {"snowy_wall_a", snow},
    {"snowy_stand", snow_wood},
    {"snowy_heap_a", snow},
    {"snowy_trunks_a", snow_wood},
    {"snowy_castle_tower_a", ice},
    {"snowy_castle_battlement_a", ice},
    {"snowy_castle_battlement_a_destroyed", {180, 190, 200}},
    {"snowy_castle_battlement_b", ice},
    {"snowy_castle_battlement_corner_a", ice},
    {"snowy_castle_battlement_corner_b", ice},
    {"snowy_castle_battlement_corner_c", ice},
    {"snowy_castle_battlement_stairs_a", ice},
    {"snowy_castle_battlement_stairs_b", ice},
    {"snowy_castle_gate_house_a", ice},
    {"snowy_castle_round_tower_a", ice},
    {"snowy_castle_square_keep_a", ice},
    {"snowy_castle_stairs_a", ice},
    {"square_keep_b", stone},
    {"square_keep_c", stone},
    {"square_keep_d", stone},
    {"square_keep_e", stone},
    {"square_keep_f", stone},
    {"square_extension_a", stone},
    {"square_stairs_a", stone},
    {"castle_courtyard_house_a", stone},
    {"castle_courtyard_house_b", stone},
    {"castle_courtyard_house_c", stone},
    {"castle_courtyard_a", stone},
    {"gatehouse_b", stone},
    {"castle_gaillard", stone},
    {"castle_e_battlement_a", stone},
    {"castle_e_battlement_c", stone},
    {"castle_e_battlement_a_destroyed", dark_stone},
    {"castle_e_sally_door_a", dark_wood},
    {"castle_e_corner", stone},
    {"castle_e_corner_b", stone},
    {"castle_e_corner_c", stone},
    {"castle_e_stairs_a", stone},
    {"castle_e_tower", stone},
    {"castle_e_gate_house_a", stone},
    {"castle_e_keep_a", stone},
    {"stand_thatched", {200, 190, 160}},
    {"stand_cloth", cloth_red},
    {"castle_e_house_a", stone},
    {"castle_e_house_b", stone},
    {"arena_block_a", {200, 180, 150}},
    {"arena_block_b", {200, 180, 150}},
    {"arena_block_c", {200, 180, 150}},
    {"arena_block_d", {200, 180, 150}},
    {"arena_block_e", {200, 180, 150}},
    {"arena_block_f", {200, 180, 150}},
    {"arena_block_g", {200, 180, 150}},
    {"arena_block_h", {200, 180, 150}},
    {"arena_block_i", {200, 180, 150}},
    {"arena_block_j", {200, 180, 150}},
    {"arena_block_j_awning", cloth_red},
    {"arena_palisade_a", wood},
    {"arena_wall_a", stone},
    {"arena_wall_b", stone},
    {"arena_barrier_a", wood},
    {"arena_barrier_b", wood},
    {"arena_barrier_c", wood},
    {"arena_tower_a", stone},
    {"arena_tower_b", stone},
    {"arena_tower_c", stone},
    {"arena_spectator_a", {180, 170, 160}},
    {"arena_spectator_b", {180, 170, 160}},
    {"arena_spectator_c", {180, 170, 160}},
    {"arena_spectator_sitting_a", {180, 170, 160}},
    {"arena_spectator_sitting_b", {180, 170, 160}},
    {"arena_spectator_sitting_c", {180, 170, 160}},
    {"courtyard_gate_a", stone},
    {"courtyard_gate_b", stone},
    {"courtyard_gate_c", stone},
    {"courtyard_gate_snowy", snow},
    {"castle_tower_a", stone},
    {"castle_battlement_a", stone},
    {"castle_battlement_b", stone},
    {"castle_battlement_c", stone},
    {"castle_battlement_a_destroyed", dark_stone},
    {"castle_battlement_b_destroyed", dark_stone},
    {"castle_battlement_corner_a", stone},
    {"castle_battlement_corner_b", stone},
    {"castle_battlement_corner_c", stone},
    {"castle_battlement_stairs_a", stone},
    {"castle_battlement_stairs_b", stone},
    {"castle_gate_house_a", stone},
    {"castle_round_tower_a", stone},
    {"castle_square_keep_a", stone},
    {"castle_stairs_a", stone},
    {"castle_drawbridge_open", wood},
    {"castle_drawbridge_closed", wood},
    {"spike_group_a", wood},
    {"spike_a", wood},
    {"belfry_a", wood},
    {"belfry_b", wood},
    {"belfry_b_platform_a", wood},
    {"belfry_old", wood},
    {"belfry_platform_a", wood},
    {"belfry_platform_b", wood},
    {"belfry_platform_old", wood},
    {"belfry_wheel", wood},
    {"belfry_wheel_old", wood},
    {"mangonel", wood},
    {"trebuchet_old", wood},
    {"trebuchet_new", wood},
    {"trebuchet_destructible", wood},
    {"stone_ball", stone},
    {"village_house_a", wood},
    {"village_house_b", wood},
    {"village_house_c", wood},
    {"village_house_d", wood},
    {"farm_house_a", wood},
    {"farm_house_b", wood},
    {"farm_house_c", wood},
    {"mountain_house_a", stone},
    {"mountain_house_b", stone},
    {"village_hut_a", wood},
    {"crude_fence", wood},
    {"crude_fence_small", wood},
    {"crude_fence_small_b", wood},
    {"ramp_12m", wood},
    {"ramp_14m", wood},
    {"siege_ladder_6m", wood},
    {"siege_ladder_8m", wood},
    {"siege_ladder_10m", wood},
    {"siege_ladder_12m", wood},
    {"siege_ladder_14m", wood},
    {"siege_ladder_move_6m", wood},
    {"siege_ladder_move_8m", wood},
    {"siege_ladder_move_10m", wood},
    {"siege_ladder_move_12m", wood},
    {"siege_ladder_move_14m", wood},
    {"portcullis", dark_metal},
    {"bed_a", wood},
    {"bed_b", wood},
    {"bed_c", wood},
    {"bed_d", wood},
    {"bed_e", wood},
    {"bed_f", wood},
    {"towngate_door_left", dark_wood},
    {"towngate_door_right", dark_wood},
    {"towngate_rectangle_door_left", dark_wood},
    {"towngate_rectangle_door_right", dark_wood},
    {"door_screen", wood},
    {"door_a", wood},
    {"door_b", wood},
    {"door_c", wood},
    {"door_d", wood},
    {"tavern_door_a", wood},
    {"tavern_door_b", wood},
    {"door_e_left", wood},
    {"door_e_right", wood},
    {"door_f_left", wood},
    {"door_f_right", wood},
    {"door_h_left", wood},
    {"door_h_right", wood},
    {"draw_bridge_a", wood},
    {"chain_1m", dark_metal},
    {"chain_2m", dark_metal},
    {"chain_5m", dark_metal},
    {"chain_10m", dark_metal},
    {"bridge_modular_a", wood},
    {"bridge_modular_b", wood},
    {"church_a", stone},
    {"church_tower_a", stone},
    {"stone_step_a", stone},
    {"stone_step_b", stone},
    {"stone_step_c", stone},
    {"stone_heap", stone},
    {"stone_heap_b", stone},
    {"panel_door_a", wood},
    {"panel_door_b", wood},
    {"smoke_stain", {100, 100, 100}},
    {"brazier_with_fire", dark_metal},
    {"cooking_fire", fire},
    {"cauldron_a", dark_metal},
    {"fry_pan_a", dark_metal},
    {"tripod_cauldron_a", dark_metal},
    {"tripod_cauldron_b", dark_metal},
    {"open_stable_a", wood},
    {"open_stable_b", wood},
    {"plate_a", {200, 180, 150}},
    {"plate_b", {200, 180, 150}},
    {"plate_c", {200, 180, 150}},
    {"lettuce", {100, 200, 80}},
    {"hanger", dark_metal},
    {"knife_eating", metal},
    {"colander", metal},
    {"ladle", metal},
    {"spoon", metal},
    {"skewer", metal},
    {"grape_a", {150, 80, 180}},
    {"grape_b", {150, 80, 180}},
    {"apple_a", {200, 50, 50}},
    {"apple_b", {200, 50, 50}},
    {"maize_a", {220, 200, 80}},
    {"maize_b", {220, 200, 80}},
    {"cabbage", {100, 200, 80}},
    {"flax_bundle", {200, 190, 160}},
    {"olive_plane", {100, 180, 80}},
    {"grapes_plane", {150, 80, 180}},
    {"date_fruit_plane", {180, 150, 80}},
    {"bowl", {200, 180, 150}},
    {"bowl_small", {200, 180, 150}},
    {"dye_blue", {50, 50, 200}},
    {"dye_red", {200, 50, 50}},
    {"dye_yellow", {220, 200, 50}},
    {"basket", wood},
    {"basket_big", wood},
    {"basket_big_green", {100, 180, 80}},
    {"leatherwork_frame", wood},
    {"cabbage_b", {100, 200, 80}},
    {"bean", {100, 180, 80}},
    {"basket_a", wood},
    {"feeding_trough_a", wood},
    {"marrow_a", {220, 200, 100}},
    {"marrow_b", {220, 200, 100}},
    {"squash_plant", {100, 180, 80}},
    {"gatehouse_new_a", stone},
    {"gatehouse_new_b", stone},
    {"gatehouse_new_snowy_a", snow},
    {"winch", wood},
    {"winch_b", wood},
    {"drawbridge", wood},
    {"gatehouse_door_left", dark_wood},
    {"gatehouse_door_right", dark_wood},
    {"cheese_a", {220, 200, 100}},
    {"cheese_b", {220, 200, 100}},
    {"cheese_slice_a", {220, 200, 100}},
    {"bread_a", {200, 180, 150}},
    {"bread_b", {200, 180, 150}},
    {"bread_slice_a", {200, 180, 150}},
    {"fish_a", {150, 180, 200}},
    {"fish_roasted_a", {200, 180, 150}},
    {"chicken_roasted", {200, 180, 150}},
    {"food_steam", {200, 200, 200}},
    {"city_smoke", {150, 150, 150}},
    {"city_fire_fly_night", fire},
    {"city_fly_day", {200, 200, 200}},
    {"flue_smoke_tall", {150, 150, 150}},
    {"flue_smoke_short", {150, 150, 150}},
    {"moon_beam", {200, 200, 255}},
    {"fire_small", fire},
    {"fire_big", fire},
    {"battle_field_smoke", {150, 150, 150}},
    {"Village_fire_big", fire},
    {"candle_a", {255, 220, 150}},
    {"candle_b", {255, 220, 150}},
    {"candle_c", {255, 220, 150}},
    {"lamp_a", metal},
    {"lamp_b", metal},
    {"hook_a", metal},
    {"window_night", {100, 100, 200}},
    {"fried_pig", {200, 180, 150}},
    {"village_oven", stone},
    {"dungeon_water_drops", water},
    {"shadow_circle_1", {50, 50, 50}},
    {"shadow_circle_2", {50, 50, 50}},
    {"shadow_square_1", {50, 50, 50}},
    {"shadow_square_2", {50, 50, 50}},
    {"wheelbarrow", wood},
    {"gourd", {220, 200, 100}},
    {"gourd_spike", wood},
    {"obstacle_fence_1", wood},
    {"obstacle_fallen_tree_a", wood},
    {"obstacle_fallen_tree_b", wood},
    {"siege_wall_a", wood},
    {"siege_large_shield_a", wood},
    {"granary_a", wood},
    {"small_wall_connect_a", stone},
    {"full_stable_a", wood},
    {"full_stable_b", wood},
    {"full_stable_c", wood},
    {"full_stable_d", wood},
    {"arabian_house_a", desert_stone},
    {"arabian_house_b", desert_stone},
    {"arabian_house_c", desert_stone},
    {"arabian_house_d", desert_stone},
    {"arabian_house_e", desert_stone},
    {"arabian_house_f", desert_stone},
    {"arabian_house_g", desert_stone},
    {"arabian_house_h", desert_stone},
    {"arabian_house_i", desert_stone},
    {"arabian_square_keep_a", desert_stone},
    {"arabian_passage_house_a", desert_stone},
    {"arabian_wall_a", desert_stone},
    {"arabian_wall_b", desert_stone},
    {"arabian_ground_a", sand},
    {"arabian_parterre_a", sand},
    {"well_shaft", stone},
    {"horse_mill", wood},
    {"horse_mill_collar", wood},
    {"arabian_stable", desert_stone},
    {"arabian_tent", {200, 180, 160}},
    {"arabian_tent_b", {200, 180, 160}},
    {"desert_plant_a", {100, 180, 80}},
    {"arabian_castle_battlement_a", desert_stone},
    {"arabian_castle_battlement_b_destroyed", {180, 160, 140}},
    {"arabian_castle_battlement_c", desert_stone},
    {"arabian_castle_battlement_d", desert_stone},
    {"arabian_castle_corner_a", desert_stone},
    {"arabian_castle_stairs", desert_stone},
    {"arabian_castle_stairs_b", desert_stone},
    {"arabian_castle_stairs_c", desert_stone},
    {"arabian_castle_battlement_section_a", desert_stone},
    {"arabian_castle_gate_house_a", desert_stone},
    {"arabian_castle_house_a", desert_stone},
    {"arabian_castle_house_b", desert_stone},
    {"arabian_castle_keep_a", desert_stone},
    {"arabian_house_a2", desert_stone},
    {"arabian_village_house_a", sand},
    {"arabian_village_house_b", sand},
    {"arabian_village_house_c", sand},
    {"arabian_village_house_d", sand},
    {"arabian_village_stable", sand},
    {"arabian_village_hut", sand},
    {"arabian_village_stairs", sand},
    {"tree_a01", leaf},
    {"stairs_a", stone},
    {"headquarters_flag_red", banner_red},
    {"headquarters_flag_blue", banner_blue},
    {"headquarters_flag_gray", {150, 150, 150}},
    {"headquarters_flag_red_code_only", banner_red},
    {"headquarters_flag_blue_code_only", banner_blue},
    {"headquarters_flag_gray_code_only", {150, 150, 150}},
    {"headquarters_pole_code_only", wood},
    {"headquarters_flag_swadian", banner_red},
    {"headquarters_flag_vaegir", banner_blue},
    {"headquarters_flag_khergit", banner_green},
    {"headquarters_flag_nord", banner_yellow},
    {"headquarters_flag_rhodok", banner_purple},
    {"headquarters_flag_sarranid", banner_orange},
    {"glow_a", glow},
    {"glow_b", glow},
    {"arabian_castle_corner_b", desert_stone},
    {"dummy_a_undestructable", flesh},
    {"cave_entrance_1", cave},
    {"pointer_arrow", {255, 50, 50}},
    {"fireplace_d_interior", fire},
    {"ship_sail_off", {200, 200, 200}},
    {"ship_sail_off_b", {200, 200, 200}},
    {"ship_c_sail_off", {200, 200, 200}},
    {"ramp_small_a", wood},
    {"castle_g_battlement_b", stone},
    {"box_a_dynamic", wood},
    {"desert_field", sand},
    {"water_river", water},
    {"viking_house_a", dark_wood},
    {"viking_house_b", dark_wood},
    {"viking_house_c", dark_wood},
    {"viking_house_d", dark_wood},
    {"viking_house_e", dark_wood},
    {"viking_stable_a", dark_wood},
    {"viking_keep", dark_wood},
    {"viking_house_c_destroy", dark_wood},
    {"viking_house_b_destroy", dark_wood},
    {"harbour_a", dark_wood},
    {"sea_foam_a", {200, 230, 240}},
    {"viking_keep_destroy", dark_wood},
    {"viking_keep_destroy_door", dark_wood},
    {"earth_tower_small_b", {180, 160, 130}},
    {"earth_gate_house_b", {180, 160, 130}},
    {"earth_tower_a", {180, 160, 130}},
    {"earth_stairs_c", {180, 160, 130}},
    {"earth_sally_gate_left", dark_wood},
    {"earth_sally_gate_right", dark_wood},
    {"barrier_box", {200, 50, 50}},
    {"barrier_capsule", {200, 50, 50}},
    {"barrier_cone", {200, 50, 50}},
    {"barrier_sphere", {200, 50, 50}},
    {"viking_keep_destroy_sally_door_right", dark_wood},
    {"viking_keep_destroy_sally_door_left", dark_wood},
    {"castle_f_door_b", dark_wood},
    {"ctf_flag_kingdom_1", banner_red},
    {"ctf_flag_kingdom_2", banner_blue},
    {"ctf_flag_kingdom_3", banner_green},
    {"ctf_flag_kingdom_4", banner_yellow},
    {"ctf_flag_kingdom_5", banner_purple},
    {"ctf_flag_kingdom_6", banner_orange},
    {"ctf_flag_kingdom_7", banner_cyan},
    {"headquarters_flag_rebel", {200, 50, 50}},
    {"arabian_lighthouse_a", desert_stone},
    {"arabian_ramp_a", desert_stone},
    {"arabian_ramp_b", desert_stone},
    {"winery_interior", wood},
    {"winery_barrel_shelf", wood},
    {"winery_wall_shelf", wood},
    {"winery_huge_barrel", wood},
    {"winery_wine_press", wood},
    {"winery_middle_barrel", wood},
    {"winery_wine_cart_small_loaded", wood},
    {"winery_wine_cart_small_empty", wood},
    {"winery_wine_cart_empty", wood},
    {"winery_wine_cart_loaded", wood},
    {"weavery_interior", wood},
    {"weavery_loom_a", wood},
    {"weavery_spinning_wheel", wood},
    {"mill_interior", wood},
    {"mill_flour_sack", {200, 190, 160}},
    {"mill_flour_sack_desk_a", {200, 190, 160}},
    {"mill_flour_sack_desk_b", {200, 190, 160}},
    {"smithy_interior", wood},
    {"smithy_grindstone_wheel", wood},
    {"smithy_forge_bellows", wood},
    {"smithy_forge", dark_metal},
    {"smithy_anvil", dark_metal},
    {"tannery_hide_a", {180, 150, 120}},
    {"tannery_hide_b", {180, 150, 120}},
    {"tannery_pools_a", {100, 150, 120}},
    {"tannery_pools_b", {100, 150, 120}},
    {"fountain", stone},
    {"rhodok_houses_a", stone},
    {"rhodok_houses_b", stone},
    {"rhodok_houses_c", stone},
    {"rhodok_houses_d", stone},
    {"rhodok_houses_e", stone},
    {"rhodok_house_passage_a", stone},
    {"bridge_b", wood},
    {"brewery_pool", {100, 150, 120}},
    {"brewery_big_bucket", wood},
    {"brewery_interior", wood},
    {"brewery_bucket_platform_a", wood},
    {"brewery_bucket_platform_b", wood},
    {"weavery_dye_pool_r", {200, 50, 50}},
    {"weavery_dye_pool_y", {220, 200, 50}},
    {"weavery_dye_pool_b", {50, 50, 200}},
    {"weavery_dye_pool_p", {200, 50, 200}},
    {"weavery_dye_pool_g", {50, 200, 50}},
    {"oil_press_interior", wood},
    {"city_swad_01", stone},
    {"city_swad_02", stone},
    {"city_swad_03", stone},
    {"city_swad_04", stone},
    {"city_swad_passage_01", stone},
    {"city_swad_05", stone},
    {"arena_block_j_a", {200, 180, 150}},
    {"arena_underway_a", stone},
    {"arena_circle_a", stone},
    {"rope_bridge_15m", wood},
    {"tree_house_a", wood},
    {"tree_house_guard_a", wood},
    {"tree_house_guard_b", wood},
    {"tree_shelter_a", wood},
    {"yellow_fall_leafs_a", autumn},
    {"rock_bridge_a", stone},
    {"suspension_bridge_a", wood},
    {"mine_a", cave},
    {"snowy_destroy_house_a", snow_wood},
    {"snowy_destroy_house_b", snow_wood},
    {"snowy_destroy_house_c", snow_wood},
    {"snowy_destroy_heap", snow},
    {"snowy_destroy_castle_a", ice},
    {"snowy_destroy_castle_b", ice},
    {"snowy_destroy_castle_c", ice},
    {"snowy_destroy_castle_d", ice},
    {"snowy_destroy_windmill", snow_wood},
    {"snowy_destroy_tree_a", snow_wood},
    {"snowy_destroy_tree_b", snow_wood},
    {"snowy_destroy_bridge_a", snow_wood},
    {"snowy_destroy_bridge_b", snow_wood},
    {"prison_cart", wood},
    {"prison_cart_door_right", wood},
    {"prison_cart_door_left", wood},
    {"multiplayer_coop_item_drop", {255, 255, 100}},
}

for i, v in ipairs(prop_colors) do
    assert(game.const["spr_" .. v[1]] == i, "something wrong with scene prop color list at " .. v[1])
end

return prop_colors